name: MacOS Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: Build Application
      run: |
        cd frontend
        npm i --package-lock-only
        npm i dmg-license
        npm install electron
        npm run build --if-present
    - name: Upload Output
      uses: actions/upload-artifact@v2
      with:
        name: aspenlog2020-macos-build
        path: frontend/dist/*.dmg
